### ISSUE TITLE
Implement SPA configuration options

### ISSUE THREAD

**Issue by timothyej** [stormpath/express-stormpath#319]
Implement SPA configuration options according to the [spec](https://github.com/stormpath/stormpath-framework-spec/blob/master/single-page-apps.md#configuration).

```yml
stormpath:
  web:
    spa:
      enabled: true
      view: index  # or other value that indicates where the entry is
```

Part of #298.
